# Author: Tom Sapletta · Part of the ifURI solution.
"""Connector generator — the autonomy that CLOSES the loop instead of waiting for a human.

When the reasoner reports a capability blocked because a scheme has no connector, this
generator scaffolds a complete, installable urirun connector from a spec (id, scheme,
handlers). Handler bodies come from the spec (deterministic) or an LLM (for novel logic);
the structure — pyproject, entry point, envelope, manifest, __init__, a smoke test — is
templated and always valid. The result is a package a node can pip-install.

    spec = {"id": "document", "scheme": "document", "summary": "...",
            "handlers": [{"route": "document/command/create", "label": "...",
                          "params": "path: str = '', text: str = ''", "body": "..."}]}
    generate(spec, dest) -> writes urirun-connector-<id>/…
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

_PYPROJECT = '''[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "urirun-connector-{id}"
version = "0.1.0"
description = "{summary}"
readme = "README.md"
requires-python = ">=3.10"
license = {{ text = "Apache-2.0" }}
authors = [{{ name = "Tom Sapletta" }}]
dependencies = ["urirun>=0.4.14"{extra_deps}]

[project.entry-points."urirun.bindings"]
{id} = "urirun_connector_{mod}.core:urirun_bindings"

[tool.setuptools.packages.find]
include = ["urirun_connector_{mod}*"]
'''

_CORE_HEADER = '''# Author: Tom Sapletta · Part of the ifURI solution — GENERATED by urirun-reasoner.
"""urirun-connector-{id} — {summary}

Generated autonomously to satisfy a capability the reasoner found blocked (no connector
served the {scheme}:// scheme). Built to URI_NATIVE_CONNECTOR_CHECKLIST: lazy imports,
handlers never raise (urirun envelope), queries in-process.
"""
from __future__ import annotations

from typing import Any

import urirun

CONNECTOR_ID = "{id}"
conn = urirun.connector(CONNECTOR_ID, scheme="{scheme}")


def _ok(**kw: Any) -> dict[str, Any]:
    return urirun.ok(connector=CONNECTOR_ID, **kw)


def _fail(msg: str, action: str, **extra: Any) -> dict[str, Any]:
    return urirun.fail(msg, connector=CONNECTOR_ID, action=action, **extra)

'''

_HANDLER = '''
@conn.handler("{route}", isolated={isolated},
              meta={{"label": "{label}"}})
def {fn}({params}) -> dict[str, Any]:
    """{doc}"""
    try:
{body}
    except Exception as exc:  # noqa: BLE001
        return _fail(str(exc), "{action}")

'''

_CORE_FOOTER = '''
def urirun_bindings() -> dict[str, Any]:
    return conn.bindings()


def connector_manifest() -> dict[str, Any]:
    return urirun.load_manifest(__package__) or {"id": CONNECTOR_ID}


def main(argv: list[str] | None = None) -> int:
    return conn.cli(argv, manifest_prose=urirun.load_manifest(__package__))


if __name__ == "__main__":
    raise SystemExit(main())
'''


def _fn_name(route: str) -> str:
    return route.replace("/", "_").replace("-", "_")


def _core(spec: dict) -> str:
    parts = [_CORE_HEADER.format(id=spec["id"], scheme=spec.get("scheme", spec["id"]),
                                 summary=spec.get("summary", ""))]
    for h in spec.get("handlers", []):
        body = "\n".join("        " + ln for ln in (h.get("body") or 'return _ok(action="todo")').splitlines())
        parts.append(_HANDLER.format(
            route=h["route"], isolated=str(bool(h.get("isolated", "/command/" in h["route"]))),
            label=h.get("label", h["route"]), fn=_fn_name(h["route"]),
            params=h.get("params", ""), doc=h.get("doc", h.get("label", h["route"])),
            body=body, action=h.get("action", spec["id"] + "-" + _fn_name(h["route"]))))
    parts.append(_CORE_FOOTER)
    return "".join(parts)


def _smoke_test(spec: dict) -> str:
    mod = spec["id"].replace("-", "_")
    lines = ["# GENERATED smoke test — every handler returns a well-formed urirun envelope.",
             f"from urirun_connector_{mod} import core\n\n",
             "def test_bindings_expose_all_routes():",
             f"    text = str(core.urirun_bindings())"]
    for h in spec.get("handlers", []):
        lines.append(f'    assert {h["route"]!r} in text')
    return "\n".join(lines) + "\n"


def generate(spec: dict, dest: str | Path) -> dict[str, Any]:
    """Write a complete connector package under ``dest/urirun-connector-<id>/``."""
    cid = spec["id"]
    mod = cid.replace("-", "_")
    root = Path(dest) / f"urirun-connector-{cid}"
    pkg = root / f"urirun_connector_{mod}"
    (pkg / "").mkdir(parents=True, exist_ok=True)
    (root / "tests").mkdir(parents=True, exist_ok=True)

    extra = "".join(f', "{d}"' for d in spec.get("deps", []))
    (root / "pyproject.toml").write_text(
        _PYPROJECT.format(id=cid, mod=mod, summary=spec.get("summary", ""), extra_deps=extra),
        encoding="utf-8")
    (pkg / "core.py").write_text(_core(spec), encoding="utf-8")
    (pkg / "__init__.py").write_text(
        f"from .core import CONNECTOR_ID, connector_manifest, main, urirun_bindings\n"
        f'__all__ = ["CONNECTOR_ID", "connector_manifest", "main", "urirun_bindings"]\n',
        encoding="utf-8")
    (root / "tests" / f"test_{mod}.py").write_text(_smoke_test(spec), encoding="utf-8")
    (root / "README.md").write_text(
        f"# urirun-connector-{cid}\n\n{spec.get('summary','')}\n\n"
        f"Generated by urirun-reasoner to serve the `{spec.get('scheme', cid)}://` scheme.\n"
        f"Part of the ifURI solution · Apache-2.0\n", encoding="utf-8")
    return {"ok": True, "path": str(root), "routes": [h["route"] for h in spec.get("handlers", [])]}
